# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StorageService/proto/storage_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*StorageService/proto/storage_service.proto\x12\x07Storage\"%\n\x04User\x12\x0f\n\x07\x63hat_id\x18\x01 \x01(\x04\x12\x0c\n\x04name\x18\x02 \x01(\t\"#\n\x05Value\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02\"I\n\nUserValues\x12\x1b\n\x04user\x18\x01 \x01(\x0b\x32\r.Storage.User\x12\x1e\n\x06values\x18\x02 \x03(\x0b\x32\x0e.Storage.Value\"-\n\x06Status\x12\x12\n\nis_success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"R\n\x0fGetDataResponse\x12\x1e\n\x06values\x18\x01 \x03(\x0b\x32\x0e.Storage.Value\x12\x1f\n\x06status\x18\x02 \x01(\x0b\x32\x0f.Storage.Status\"D\n\x07IsExist\x12\'\n\x0erequest_status\x18\x01 \x01(\x0b\x32\x0f.Storage.Status\x12\x10\n\x08is_exist\x18\x02 \x01(\x08\x32\x85\x02\n\x07Storage\x12\x36\n\tgetValues\x12\r.Storage.User\x1a\x18.Storage.GetDataResponse\"\x00\x12\x33\n\tsetValues\x12\x13.Storage.UserValues\x1a\x0f.Storage.Status\"\x00\x12.\n\nremoveUser\x12\r.Storage.User\x1a\x0f.Storage.Status\"\x00\x12+\n\x07\x61\x64\x64User\x12\r.Storage.User\x1a\x0f.Storage.Status\"\x00\x12\x30\n\x0buserIsExist\x12\r.Storage.User\x1a\x10.Storage.IsExist\"\x00\x62\x06proto3')



_USER = DESCRIPTOR.message_types_by_name['User']
_VALUE = DESCRIPTOR.message_types_by_name['Value']
_USERVALUES = DESCRIPTOR.message_types_by_name['UserValues']
_STATUS = DESCRIPTOR.message_types_by_name['Status']
_GETDATARESPONSE = DESCRIPTOR.message_types_by_name['GetDataResponse']
_ISEXIST = DESCRIPTOR.message_types_by_name['IsExist']
User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'StorageService.proto.storage_service_pb2'
  # @@protoc_insertion_point(class_scope:Storage.User)
  })
_sym_db.RegisterMessage(User)

Value = _reflection.GeneratedProtocolMessageType('Value', (_message.Message,), {
  'DESCRIPTOR' : _VALUE,
  '__module__' : 'StorageService.proto.storage_service_pb2'
  # @@protoc_insertion_point(class_scope:Storage.Value)
  })
_sym_db.RegisterMessage(Value)

UserValues = _reflection.GeneratedProtocolMessageType('UserValues', (_message.Message,), {
  'DESCRIPTOR' : _USERVALUES,
  '__module__' : 'StorageService.proto.storage_service_pb2'
  # @@protoc_insertion_point(class_scope:Storage.UserValues)
  })
_sym_db.RegisterMessage(UserValues)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'StorageService.proto.storage_service_pb2'
  # @@protoc_insertion_point(class_scope:Storage.Status)
  })
_sym_db.RegisterMessage(Status)

GetDataResponse = _reflection.GeneratedProtocolMessageType('GetDataResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETDATARESPONSE,
  '__module__' : 'StorageService.proto.storage_service_pb2'
  # @@protoc_insertion_point(class_scope:Storage.GetDataResponse)
  })
_sym_db.RegisterMessage(GetDataResponse)

IsExist = _reflection.GeneratedProtocolMessageType('IsExist', (_message.Message,), {
  'DESCRIPTOR' : _ISEXIST,
  '__module__' : 'StorageService.proto.storage_service_pb2'
  # @@protoc_insertion_point(class_scope:Storage.IsExist)
  })
_sym_db.RegisterMessage(IsExist)

_STORAGE = DESCRIPTOR.services_by_name['Storage']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USER._serialized_start=55
  _USER._serialized_end=92
  _VALUE._serialized_start=94
  _VALUE._serialized_end=129
  _USERVALUES._serialized_start=131
  _USERVALUES._serialized_end=204
  _STATUS._serialized_start=206
  _STATUS._serialized_end=251
  _GETDATARESPONSE._serialized_start=253
  _GETDATARESPONSE._serialized_end=335
  _ISEXIST._serialized_start=337
  _ISEXIST._serialized_end=405
  _STORAGE._serialized_start=408
  _STORAGE._serialized_end=669
# @@protoc_insertion_point(module_scope)
